spring.application.name=web
# PostgreSQL database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/IskmAdminDb?createDatabaseIfNotExist=true
spring.datasource.username=${postgresql.username}
spring.datasource.password=${postgresql.password}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true


# JPA/Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

razorpay.key.id=rzp_test_RMxF33uZbAyUO0
razorpay.key.secret=DWdYxkYcOxBZQ5yT8sueiWHw

