package org.iskm.admin.web.repository;

import java.time.LocalDateTime;
import java.util.List;

import org.iskm.admin.web.model.entity.Content;
import org.springframework.data.jpa.domain.Specification;
import org.springframework.data.jpa.repository.JpaRepository;

public interface ContentRepository extends JpaRepository<Content, Long> {
    // You get save(), findById(), findAll() and more auto-generated by JPA
	
	List<Content> findByStatus(String status);

	List<Content> findAll(Specification<Content> spec);

}

